version: '3.8'

services:
  mlflow:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      MLFLOW_TRACKING_URI: postgresql://mlflow:password@postgres:5432/mlflow_db
      MLFLOW_BACKEND_STORE_URI: postgresql://mlflow:password@postgres:5432/mlflow_db
      MLFLOW_ARTIFACT_ROOT: /mlflow/mlruns
    depends_on:
      - postgres
    networks:
      - mlflow_network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mlflow_network

volumes:
  pgdata:

networks:
  mlflow_network:
    driver: bridge
