version: '3.8'

services:
  mlflow:
    image: python:3.10
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./mlflow.db:/mlflow.db
    command: >
      sh -c "pip install mlflow &&
             mlflow server --host 0.0.0.0 
                          --backend-store-uri sqlite:///mlflow.db 
                          --default-artifact-root file:///mlruns"
    
  model-service:
    build:
      context: .
      dockerfile: Dockerfile.model
    ports:
      - "8000:8000"
    depends_on:
      - mlflow

volumes:
  mlruns:
  mlflow-db: