services:
  mlflow:
    build: .                # <--- build à partir de ton Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    networks:
      - mlflow_network
    depends_on:
      - postgres            # attendre que postgres démarre

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    networks:
      - mlflow_network

networks:
  mlflow_network:
    driver: bridge
