scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['localhost:8000']

name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t myapi .

      - name: Run API
        run: docker run -p 5000:5000 myapi
