name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest  # Utilise la dernière version stable d'Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # Assure-toi de spécifier une version stable de Python

    - name: Install dependencies
      run: |
        pip install -r src/requirements.txt

    - name: Run training script with MLflow
      run: |
        python src/train_model.py
