name: CI/CD MLOps
on: [push]
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installer Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Installer dépendances
        run: pip install -r requirements.txt
      - name: Exécuter le pipeline
        run: python src/train.