name: CI/CD MLOps

on:
  push:
    branches:
      - main  # Utilise "main" si ta branche par défaut est main, sinon utilise "master"

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Clear pip cache
        run: |
          rm -rf ~/.cache/pip

      - name: List files in src directory
        run: ls -R Prediction_Consommation-de-carburant/src/

      - name: Install dependencies
        run: |
          pip install -r Prediction_Consommation-de-carburant/src/requirements.txt

      - name: Verify installation of mlflow
        run: |
          python -c "import mlflow; print('MLflow version:', mlflow.__version__)"

      - name: Run the training pipeline
        run: python src/train_model.py
        working-directory: ./Prediction_Consommation-de-carburant/src

        env:
          MLFLOW_TRACKING_URI: http://localhost:5000
          MLFLOW_EXPERIMENT_NAME: Prediction_Consommation_Carburant

      - name: Commit model and artifacts to MLflow
        run: |
          echo "Logging model to MLflow"
          mlflow.log_artifact "models/rf_reg_model.pkl"  # Enregistre ton modèle RandomForest
          mlflow.log_artifact "models/scaler.pkl"        # Enregistre ton scaler
          mlflow.log_model rf_reg_model "rf_reg_model"   # Enregistre le modèle dans MLflow
          mlflow.log_model scaler "scaler_model"         # Enregistre le scaler dans MLflow
        continue-on-error: true
