name: MLOps Pipeline

on:
  push:
    branches: [ main ]  # Le pipeline se déclenche à chaque push vers la branche "main"

jobs:
  train:
    runs-on: ubuntu-latest  # Utilisation de l'environnement Ubuntu pour l'exécution

    steps:
    - name: Checkout
      uses: actions/checkout@v3  # Récupérer le code source du dépôt

    - name: Setup Python
      uses: actions/setup-python@v4  # Installer Python
      with:
        python-version: 3.10  # Version de Python spécifiée

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Installer les dépendances spécifiées dans requirements.txt

    - name: Run training with MLflow
      run: |
        python src/train_model.py  # Exécuter le script Python qui entraîne le modèle avec MLflow
