name: MLOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  train:
    runs-on: ubuntu-24.04
    
    services:
      mlflow-server:
        image: python:3.10
        ports:
          - "5000:5000"
        env:
          MLFLOW_TRACKING_URI: http://localhost:5000
        volumes:
          - ./mlruns:/mlruns
          - ./mlflow.db:/mlflow.db
        run: |
          pip install mlflow
          mlflow server \
            --host 0.0.0.0 \
            --port 5000 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root file:///mlruns

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install mlflow scikit-learn pandas joblib
    
    - name: Wait for MLflow server
      run: |
        echo "Waiting for MLflow server to start..."
        while ! nc -z localhost 5000; do
          sleep 1
        done
        echo "MLflow server is ready!"
    
    - name: Run training
      env:
        MLFLOW_TRACKING_URI: http://localhost:5000
      run: |
        python src/train_model.py
    
    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mlflow-artifacts
        path: |
          mlruns/
          mlflow.db
        retention-days: 5