name: CI/CD MLOps Pipeline

on:
  push:
    branches: [main]

jobs:
  train:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Prediction_Consommation-de-carburant

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install mlflow==2.10.1 scikit-learn==1.4.0 pandas==2.0.3 numpy==1.24.4 joblib==1.3.2

    - name: Verify structure
      run: |
        ls -R
        echo "Current path: $(pwd)"
        echo "MLflow version: $(python -c 'import mlflow; print(mlflow.__version__)')"

    - name: Run training
      run: python src/train_model.py
      env:
        CI: "true"
        MLFLOW_TRACKING_URI: "file:///tmp/mlruns"
        MLFLOW_EXPERIMENT_NAME: "Prediction_Consommation_Carburant"

    - name: Upload MLflow artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-artifacts
        path: /tmp/mlruns